export { default as Main } from './Main/Main'
export { default as BlogPage } from './Blog/BlogPage'
export { default as ProjectPage } from './Project/ProjectPage'
export { default as Sony } from './Sony/Sony'
export { default as Caps_Redesign } from './Caps_Redesign/Caps_Redesign'
export {default as CDC} from './CDC/CDC'